#!/bin/bash
# Background
for i in {0..255} ; do
	printf "\x1b[48;5;%sm%3d\e[0m " "$i" "$i"
	if (( i == 15 )) || (( i > 15 )) && (( (i-15) % 18 == 0 )); then
		printf "\n";
	fi
done
printf "\n"
# Foreground
for i in {0..255} ; do
        printf "\x1b[38;5;%sm%3d\e[0m " "$i" "$i"
        if (( i == 15 )) || (( i > 15 )) && (( (i-15) % 18 == 0 )); then
                printf "\n";
        fi
done
printf "\n"
